#!/usr/bin/python3
# -*- coding: utf-8 -*-

#
# Merges individual files for each context into a large contexts.yaml file.
#
# Usage:
#
# Author: rja
#
# Changes:
# 2025-05-12 (rja)
# - initial version

import os

indir = "contexts"

if os.path.isdir(indir):
    print("# This file is auto-generated from the individual contexts in")
    print("# " + indir + " using src/merge_contexts_yaml.py.")
    print("# DO NOT EDIT THIS FILE.")
    for fname in sorted(os.listdir(indir)):
        context, ext = os.path.splitext(fname)
        if ext == '.yaml':
            print(context + ".cxt:")
            with open(os.path.join(indir, fname), "rt") as f:
                for line in f:
                    print("  " + line.strip())
            print()
