name: Merge individual context metadata (YAML) files into a joint contexts.yaml
on: [push]
permissions:
  contents: write
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Merge
        run: ./src/merge_contexts_yaml.py > contexts.yaml
      - name: Commit
        run: |
          git config --global user.name 'rjoberon'
          git config --global user.email 'rjoberon@users.noreply.github.com'
          git add contexts.yaml
          git commit -m "Created merged file"
          git push
