name: Merge YAML Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  merge-yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Run YAML merge script
        run: python scripts/merge_contexts_metadata.py

      - name: Commit and push merged YAML file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add merged-contexts-metadata.yaml
          git diff --quiet && git diff --staged --quiet || git commit -m "Update contexts metadata file"
          git push
